<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Bussiness</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="log4net">
      <HintPath>$(RuntimeBinaryRoot)\Fight\log4net.dll</HintPath>
    </Reference>
    <Reference Include="SqlDataProvider">
      <HintPath>$(RuntimeBinaryRoot)\Fight\SqlDataProvider.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="Game.Base">
      <HintPath>$(RuntimeBinaryRoot)\Fight\Game.Base.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Core" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web" />
    <Reference Include="System.Data"></Reference>
    <Reference Include="System.Xml" />
  </ItemGroup>
</Project>
