namespace Game.Server.Packets
{

public enum RingStationPackageType
{
	RINGSTATION_VIEWINFO = 1,
	RINGSTATION_BUYCOUNTORTIME,
	RINGSTATION_ARMORY,
	RINGSTATION_NEWBATTLEFIELD,
	RINGSTATION_CHALLENGE,
	RINGSTATION_FIGHTFLAG,
	RINGSTATION_SENDSIGNMSG
}
}
