namespace Game.Server.Packets;

public enum CampPackageType
{
	ADD_ROLE_LIST = 1,
	ROLE_MOVE = 2,
	REMOVE_ROLE = 3,
	ADD_MONSTER_LIST = 4,
	ENTER_MONSTER_FIGHT = 5,
	INIT_SECEN = 6,
	MONSTER_STATE_CHANGE = 7,
	PLAYER_STATE_CHANGE = 8,
	MAP_CHANGE = 9,
	PVP_TO_FIGHT = 16,
	CAPTURE_MAP = 17,
	RESURRECT = 18,
	WIN_COUNT_PTP = 19,
	CAMP_SOCER_RANK = 20,
	PER_SCORE_RANK = 21,
	UPDATE_SCORE = 22,
	ACTION_ISOPEN = 10,
	DOOR_STATUS = 23,
	OUT_CAMPBATTLE = 25
}
