namespace Game.Server.Packets;

public enum ChristmasPackageType
{
	CHRISTMAS_OPENORCLOSE = 16,
	CHRISTMAS_PLAYERING_SNOWMAN_ENTER = 17,
	CHRISTMAS_MAKING_SNOWMAN_ENTER = 24,
	GET_PAKCS_TO_PLAYER = 27,
	CHRISTMAS_PACKS = 26,
	CHRISTMAS_SCORECONVERT = 5,
	FIGHT_SPIRIT_LEVELUP = 25,
	MOVE = 21,
	ADDPLAYER = 18,
	CHRISTMAS_EXIT = 19,
	PLAYER_STATUE = 20,
	CHRISTMAS_MONSTER = 22,
	FIGHT_MONSTER = CHRISTMAS_MONSTER,
	CHRISTMAS_ROOM_SPEAK = 28,
	CHRISTMAS_BUY_TIMER = 29,
	UPDATE_TIMES_ROOM = 30
}
