namespace Game.Server.Packets;

public enum GuildMemberWeekPackageType
{
	OPEN = 7,
	PLAYERTOP10 = 8,
	ADDPOINTBOOK10 = 9,
	GET_MYRUNKING = 11,
	ADDPOINTBOOKRECORD = 10,
	UPADDPOINTBOOK = 12,
	SHOWACTIVITYEND = 13,
	ENTER_GAME = PLAYERTOP10,
	CLOSE = ADDPOINTBOOK10,
	SEND_ADDRUNKING = ADDPOINTBOOKRECORD,
	FINISHACTIVITY = 53,
	SHOWRUNKING = 54
}
