namespace Game.Server.Packets;

public enum LanternriddlesPackageType
{
	LANTERNRIDDLES_BEGIN = 37,
	LANTERNRIDDLES_QUESTION,
	LANTERNRIDDLES_ANSWERRESULT,
	LANTERNRIDDLES_ANSWER,
	LANTERNRIDDLES_SKILL,
	LANTERNRIDDLES_RANKINFO,
	LANTERNRIDDLES_BEGINTIPS
}
