<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Game.Base</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="log4net">
      <HintPath>$(RuntimeBinaryRoot)\center\log4net.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml"></Reference>
    <Reference Include="System.Configuration"></Reference>
    <Reference Include="zlib.net">
      <HintPath>$(RuntimeBinaryRoot)\center\zlib.net.dll</HintPath>
    </Reference>
    <Reference Include="System.Core"></Reference>
  </ItemGroup>
</Project>
