namespace Bussiness
{
public enum ChatInputView
{
	ADMIN_NOTICE = 8,
	BIG_BUGLE = 0,
	CHURCH_CHAT = 9,
	CONSORTIA = 3,
	CROSS_BUGLE = 15,
	CROSS_NOTICE = 12,
	CURRENT = 5,
	DEFENSE_TIP = 10,
	DEFY_AFFICHE = 11,
	HOTSPRING_ROOM = 13,
	PRIVATE = 2,
	SMALL_BUGLE = 1,
	SYS_NOTICE = 6,
	SYS_TIP = 7,
	TEAM = 4,
	GM_NOTICE = 14,
	WORLDBOSS_ROOM = 20,
	CHRISTMAS_CHAT = 25
}

}
