namespace Game.Logic
{
public enum ePetEffectType
{
	AddAgilityEffect = 1,
	AddAttackEffect = 2,
	AddBloodEffect = 3,
	AddDamageEffect = 4,
	AddDefenceEffect = 5,
	AddLuckyEffect = 6,
	FatalEffect = 7,
	IceFronzeEffect = 9,
	IceFronzeEquipEffect = 10,
	NoHoleEffect = 12,
	NoHoleEquipEffect = 13,
	ReduceDamageEffect = 14,
	SealEffect = 15,
	AtomBomb = 16,
	ArmorPiercer = 17,
	SealEquipEffect = 18,
	AddTurnEquipEffect = 19,
	AddDander = 20,
	ReflexDamageEquipEffect = 21,
	ReduceStrengthEffect = 22,
	ContinueDamageEffect = 23,
	AddBombEquipEffect = 24,
	AvoidDamageEffect = 25,
	MakeCriticalEffect = 26,
	AssimilateDamageEffect = 27,
	AssimilateBloodEffect = 28,
	ReflexDamageEffect = 29,
	ContinueReduceBaseDamageEquipEffect = 30,
	ReduceStrengthEquipEffect = 31,
	ContinueReduceBloodEquipEffect = 32,
	ContinueReduceBloodEffect = 33,
	LockDirectionEquipEffect = 34,
	LockDirectionEffect = 35,
	ContinueReduceBaseDamageEffect = 36,
	RecoverBloodEffect = 37,
	ContinueReduceDamageEffect = 38,
	PetReduceAttackEffect = 39,
	PetReduceAttackEquipEffect = 40,
	PetDefendEquipEffect = 41,
	PetStopMovingEffect = 42,
	PetStopMovingEquipEffect = 43,
	PetPlusGuardEquipEffect = 44,
	PetPlusDameEquipEffect = 45,
	PetRemovePlusDameEquipEffect = 46,
	PetRemovePlusGuardEquipEffect = 47,
	PetPlusOneMpEquipEffect = 48,
	PetPlusTwoMpEquipEffect = 49,
	PetPlusThreeMpEquipEffect = 50,
	PetPlusAllTwoMpEquipEffect = 51,
	PetAttackAroundEquipEffect = PetPlusAllTwoMpEquipEffect,
	PetAddAttackEquipEffect = 52,
	PetAddLuckEquipEffect = 53,
	PetReduceDefendEquipEffect = 54,
	PetAlwayNoHoleEquipEffect = 55,
	PetRemoveV3BatteryEquipEffect = 56,
	PetFieryAntBallPlusdefend = 57
}

}
