<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GameServerScripts</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Game.Logic">
      <HintPath>$(RuntimeBinaryRoot)\Fight\Game.Logic.dll</HintPath>
    </Reference>
    <Reference Include="Game.Base">
      <HintPath>$(RuntimeBinaryRoot)\Fight\Game.Base.dll</HintPath>
    </Reference>
    <Reference Include="SqlDataProvider">
      <HintPath>$(RuntimeBinaryRoot)\Fight\SqlDataProvider.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
