<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\GunnyLauncher.Core\GunnyLauncher.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>GunnyLauncher</AssemblyName>
    <RootNamespace>GunnyLauncher.App</RootNamespace>
  </PropertyGroup>
</Project>
